### ISSUE TITLE
Update to napari-yaml plugin definition

### ISSUE THREAD

**Issue by haesleinhuepf** [haesleinhuepf/napari-segment-blobs-and-things-with-membranes#45]
git-bob think about how to update the code in this repository to make use of napari's yml plugin definition. You find the documentation for this file format under the headline "npe2 contributions" here: https://github.com/napari/docs/blob/main/docs/plugins/advanced_topics/npe2_migration_guide.md and here: https://github.com/napari/docs/blob/142ac9a29857a5db5fcc5c3960c3d4b2c1c83073/docs/naps/6-contributable-menus.md
We basically need to convert all `@register_function(menu="My menu")` decorations in __init__.py into the mentioned yaml format, e.g.: 
```
contributions:
  commands:
    - id: nsbatwm.my_menu
      title: My menu
      python_name: nsbatwm.my_menu

  menus:
    napari/layers/context:
      - my_menu: nsbatwm.my_menu
```
